version: 2
jobs:
  build:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout  # Получение исходного кода      
      # - setup_remote_docker               
      # - run:
          # name: Build Docker Image
          # command: docker build -t angular-shop:latest .

  deploy:
    # machine:
      # enabled: true
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - setup_remote_docker          
      - run:
          name: Deploy to GCP
          command: |
            docker build -t angular-shop:latest .
            docker login -u _json_key -p "$(echo $GCP_SERVICE_KEY)" https://gcr.io
            docker tag angular-shop gcr.io/prod-398815/angular-shop
            docker push gcr.io/prod-398815/angular-shop
            
  deploy-to-gcp:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Set GCP Project ID
          command: echo "export CLOUDSDK_CORE_PROJECT=prod-398815" >> $BASH_ENV
    
      - run:
          name: Authenticate with GCP
          command: echo $GCP_SERVICE_KEY > /tmp/keyfile.json && gcloud auth activate-service-account --key-file /tmp/keyfile.json
      - run:
          name: Deploy to GCP
          command: |
            gcloud compute instances create my-instance-name \
              --image-family=ubuntu-1804-lts \
              --image-project=ubuntu-os-cloud \
              --machine-type=n1-standard-1 \
              --zone=europe-central2-a \
              --tags=http-server,https-server

            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - deploy-to-gcp:
          requires:
            - deploy
